### PR TITLE
Switch proxies to use esp-idf instead of arduino

### PR DESCRIPTION
**Pull request by bdraco**
This saves ~50K of ram and makes the proxies more stable, but we need 2022.12.x for this to work.

### CODE REVIEW

**Comment by nagyrobi** [comment]
Will this work on Ethenet boards? Most of the Ethernet components are still arduino-dependant...

**Comment by bdraco** [comment]
It should with the idf upgrade. I can confirm the Poe olimex board is working

**Comment by nagyrobi** [comment]
Tested on an Olimex myself and indeed it's working in the latest beta. 
In 2022.11 the config validation rejects `ethernet` with `esp-idf`.
Wonder which PR changed this?

**Comment by nagyrobi** [comment]
Done in: https://github.com/esphome/esphome/pull/3564
Available from 2022.12 for LAN8720, RTL8201, DP83848, IP101 modules.

**Comment by bdraco** [comment]
> Tested on an Olimex ESP32-POE-ISO-EA and a WirelessTag WT32-ETH01 myself and indeed it's working in the latest beta. Both `type: LAN8720`
> 
> In 2022.11 the config validation rejects `ethernet` with `esp-idf`.
> 
> Wonder which PR changed this?

It's the idf upgrade jesse did afaik

**Comment by bdraco** [comment]
Looks like you found the exact pr 👍. Awesome

**Comment by nagyrobi** [comment]
Awesome indeed

**Comment by Nardol** [comment]
Will `captive_portal` be compatible with esp-idf in ESPHome 2022.12?
In the actual state compilation fails and the PR checks also confirm it, for example for m5stack-atom.
`async_tcp` make also compilation fail.

**Comment by nagyrobi** [comment]
Try manually https://github.com/esphome/esphome/pull/3500

**Comment by jesserockz** [comment]
We can change the CI files to point to ESPHome beta so we can get these firmwares out and people can use them alongside the Home Assistant release this week.

**Comment by bdraco** [comment]
That would be great if you get these to build before they release party demo

**Comment by nagyrobi** [comment]
Except config containing `captive_portal`...!

**Comment by jesserockz** [comment]
I have commented out the captive portals on the 2 wifi configs for now. 

I think its acceptable as these firmwares are meant to be flashed via the website which also uses `improv_serial` to write the wifi credentials at the same time so there is no real need for the captive portal.

**Comment by bdraco** [comment]
Yes, that makes sense to me 👍

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Watch here for build progress
https://github.com/esphome/bluetooth-proxies/actions/runs/3641898979

It sometimes fails with concurrent git, i will keep an eye on it

**Pull request merged**
