### PR TITLE
Turn on active mode on bluetooth proxies

### PR DESCRIPTION
**Pull request by jesserockz**

### CODE REVIEW

**Review by balloob — APPROVED** [review]

**Comment by niemyjski** [comment]
Any idea when proxies will go live? I updated to latest ESPHome release and updating firmware is blocked because the config is pointing to main:  ` esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main` makes me wonder if there should be some kind of marker like latest?

**Comment by balloob** [comment]
Run ESPHome dev branch to access `active`. 

Good point on breaking normal updates now in ESPHome. We will think about it.

**Comment by jesserockz** [comment]
@niemyjski I have added repo tags/releases so you can change `@main` to `@v1` (or `@v2`) in your local adopted yaml to change between.

**Comment by kellyatkinson** [comment]
Man, I must have received my new Atom Lite devices on the wrong day. Flashing them results in an immediate error that 'active' isn't a valid option for 'bluetooth_proxy'. It sounds like this will be resolved soon?

**Comment by Nardol** [comment]
This is available on the dev version of ESPHome, not yet on stable.

**Comment by balloob** [comment]
Temporary workaround is to install from https://esphome.github.io/bluetooth-proxies/

**Pull request merged**
