### PR TITLE
Update gl-s10.yaml

### PR DESCRIPTION
**Pull request by Go0oSer**
Resolves packet loss issue with v2.1 of GL-S10.

### CODE REVIEW

**Comment by trvrnrth** [comment]
Looks to have resolved the connection flakiness with my device 🥳

**Review by liudger — APPROVED** [review]
Tested the code on GL-S10 and the network connection is stable!

LGTM

**Comment by balloob** [comment]
As stated in our documentation, our website is only supporting revision 2.3.

**Comment by raoulbhatia** [comment]
@balloob I am curios,
Before closing, did you test the current ethernet implementation with hardware rev 2.3 and confirm this fix is not required anymore?

It would be good, if you could share more details upon close.

Thanks,
Raoul

**Comment by jesserockz** [comment]
If someone has a v2.3 revision of this board and can verify these changes work, then we will gladly accept it in.

But if the hardware changed and requires `clk_mode: GPIO17_OUT` then it doesn't make sense to change.

I personally have a v2.1 revision and the change works there.

**Comment by trvrnrth** [comment]
Accepting the change in the form of a comment regarding the required config for v2.1 (as is already the case for v1.0) would seem like a better solution than just closing the PR if this does not apply to v2.3 devices.

**Comment by Go0oSer** [comment]
This is my first PR.  I did not realize something similar was discussed a few weeks ago.  I wanted to make the fix known for those that want them.  I would be happy to submit a PR with a comment for v2.1 if that works.  I think that is a reasonable solution and makes sure the fix isn't lost.

**Comment by jesserockz** [comment]
#79

**Review by jesserockz — APPROVED** [review]

**Comment by raoulbhatia** [comment]
Thanks @jesserockz

**Pull request merged**
