### PR TITLE
Add lily go t eth poe

### PR DESCRIPTION
**Pull request by kquinsland**
There is another common PoE powered ESP32 module commonly available on Ali Express: the ttgo-poe module.

E.g.:
https://www.aliexpress.com/item/2255800936677694.html

There are more than a few threads out there asking how to get the board working with ESPHome since there is no explicitly platform.io configuration for it.

I spent some time yesterday getting one to work and can confirm that the module works with a standard `esp32dev` board ID.

This PR is effectively `ln -s` on the generic file but with the correct ETH configuration already added.

I figured that would be more helpful than just creating a "FYI, this ttgo board works with the generic file after you add in this configuration ..." issue.

### CODE REVIEW

**Comment by balloob** [comment]
Please see #6 as an example of what is needed to add a new device.

**Comment by kquinsland** [comment]
I've updated the static html / GHA flow; not sure how I missed that originally :(.

All the static images were run through a simple EXIF strip tool; some images are a few KB smaller w/o any visual changes. This will make the page load _slightly_ faster.

**Comment by balloob** [comment]
Looking good!

Can you update the lily picture to be in the same style as the other pictures; including a vendor logo in top right

**Comment by kquinsland** [comment]
I found a different image that has the skeuomorphic view to match the rest rather than top down and gimped in their logo

**Comment by balloob** [comment]
We're getting there 😄  The picture also needs to be square, 800x800px 😬

**Comment by nagyrobi** [comment]
And maybe add a little more white border around it (=make the board look a bit smaller)

**Comment by kquinsland** [comment]
Thanks for the assist w/ the images, @balloob .  Can you tell that i'm not a Front end dev / don't know my way around gimp? :D.

**Pull request merged**
